plugins {
    id 'com.gradleup.shadow' version '8.3.5'
}

repositories {
    mavenCentral()
    maven {
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }
}

dependencies {

    implementation project(':')  // Root project
    compileOnly "io.papermc.paper:paper-api:1.21.1-R0.1-SNAPSHOT"
    testImplementation "io.papermc.paper:paper-api:1.21.1-R0.1-SNAPSHOT"

}

shadowJar {
    relocate 'io.netty', 'net.buildtheearth.terraminusminus.shaded.io.netty'

    dependencies {
        include(dependency('io.netty:.*'))
        include(project(':'))
    }

    archiveClassifier.set('')
}

processResources {
    inputs.property "version", project.version
    filesMatching("paper-plugin.yml") {
        expand 'version': project.version
    }
}

tasks.assemble.dependsOn shadowJar

publishing {
    publications {
        terraminusminusBukkit(MavenPublication) {
            groupId = project.group
            artifactId = "terraminusminus-bukkit"
            version = project.version
            project.shadow.component(it)
        }
    }
}