repositories {
    maven { // For bukkit api bindings
        name = "SpigotMC"
        url = "https://hub.spigotmc.org/nexus/content/repositories/snapshots/"
    }
}

shadowJar {
    archiveClassifier.set('')
}
jar.enabled = false
assemble.dependsOn shadowJar

evaluationDependsOn(':')

dependencies {

    shadowed project(path: ':', configuration: 'shadow')
    compileOnly "org.spigotmc:spigot-api:1.21.8-R0.1-SNAPSHOT"
    testImplementation "org.spigotmc:spigot-api:1.21.8-R0.1-SNAPSHOT"

}

publishing {
    publications {
        terraminusminusBukkit(MavenPublication) {
            groupId = project.group
            artifactId = "terraminusminus-bukkit"
            version = project.version
            project.shadow.component(it)
        }
    }
}