repositories {
    maven { // For bukkit api bindings
        name = "SpigotMC"
        url = "https://hub.spigotmc.org/nexus/content/repositories/snapshots/"
    }
}

shadowJar {
    archiveClassifier.set('')
}
jar.enabled = false
assemble.dependsOn shadowJar

evaluationDependsOn(':')

dependencies {

    api project(':')
    compileOnly "org.spigotmc:spigot-api:1.21.8-R0.1-SNAPSHOT"
    testImplementation "org.spigotmc:spigot-api:1.21.8-R0.1-SNAPSHOT"

}

publishing {
    publications {
        terraminusminusBukkit(MavenPublication) {
            groupId = project.group
            artifactId = "terraminusminus-bukkit"
            version = project.version
            from components.java

            artifact shadowJar

            pom.withXml {
                def dependenciesNode = asNode().dependencies[0]
                if (dependenciesNode) {
                    dependenciesNode.children().findAll {
                        it.artifactId.text() == 'terraminusminus-core'
                    }.each {
                        dependenciesNode.remove(it)
                    }
                }
            }
        }
    }
}